### PR TITLE
add german translation

### PR DESCRIPTION
**Pull request by Phu2**
replace english descriptions with german translation, mainly from deepl.com

### CODE REVIEW

**Review by vdb-online — CHANGES_REQUESTED** [review]
Please remove second commit from this PR

**Review by vdb-online — APPROVED** [review]

**Comment by Phu2** [comment]
Hey @vdb-org/library-carpentry please have a look at the proposed german translation, thanks :)
(Btw, i'm learning Github and it's collaboration features.)

**Comment by vdb-online** [comment]
I did a rebase in order to remove the second commit... revert would have been better.

**Comment by Phu2** [comment]
I did a rebase in order to remove the second commit... revert would have been better.

**Comment by Phu2** [comment]
no translation needed

**Pull request closed without merging**
